<!DOCTYPE html>
<html lang="<?php print $language ?>" dir="ltr">
	<head>
		<title><?php print isset($title)?$title." | ":"" ?><?php print $appName ?></title>
		<meta charset="utf-8" />
		<meta name="author" content="" />
		<meta name="viewport" content="initial-scale=1.0">
		<meta name="viewport" content="width=device-width">
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<meta property="og:image" content=""/>
		<meta property="og:title" content="" />
		<link rel="icon" type="image/vnd.microsoft.icon" href="/theme/ui/favicon.png" />
		<link rel="stylesheet" type="text/css" href="/theme/styles.css" />
		<!--[if lt IE 9]><link rel="stylesheet" href="/theme/fixes/ie8.css" /><![endif]-->
		<!--[if lt IE 8]><link rel="stylesheet" href="/theme/fixes/ie7.css" /><![endif]-->
		<!--[if lt IE 7]><link rel="stylesheet" href="/theme/fixes/rip.css" /><![endif]-->
		<script type="text/javascript">document.documentElement.className += " js";</script>
		<!--[if lt IE 9]>
			<script src="/theme/fixes/html5shiv.min.js" type="text/javascript"></script>
			<script src="/theme/fixes/respond.min.js" type="text/javascript"></script>
		<![endif]-->
		<script src="/web.js"></script>
		<script src="/theme/scripts.js"></script>
		<!--[if lt IE 9]><script src="/theme/fixes/ie8.js"></script><![endif]-->
		<!--[if lt IE 8]><script src="/theme/fixes/ie7.js"></script><![endif]-->
		<!--[if lt IE 7]><script src="/theme/fixes/rip.js"></script><![endif]-->
	</head>
	<body>
		<section id="mainContent"><?php isset($content) && print($content) ?></section>
	</body>
</html>
