<!DOCTYPE html>
<html lang="<?php print $language ?>" dir="ltr">
	<head>
		<title><?php print $title ?></title>
		<meta charset="utf-8" />
		<meta name="author" content="" />
		<meta name = "viewport" content = "initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no, width = device-width"/>
		<script src="/themes/mobile/components/config.js" type="text/javascript"></script>
		<script src="/themes/mobile/components/ljs/l.min.js" type="text/javascript"></script>
		<script type="text/javascript">
			ljs.addAliases(jlsConfig);
		</script>
		<script src="/themes/mobile/scripts/main.js" type="text/javascript"></script>
		<link rel="stylesheet" href="/themes/mobile/styles/all.css" />
	</head>
	<body>
		<?php isset($content) && print($content) ?>
	</body>
</html>
